### ISSUE TITLE
Not found QK-article.csv in TenRec.zip file

### ISSUE THREAD

**Issue by PeiJieSun** [yuangh-x/2022-NIPS-Tenrec#1]
Hi, thank you for your guys sharing the large dataset, I have downloaded the TenRec.zip via the link  https://drive.google.com/file/d/1R1JhdT9CHzT3qBJODz09pVpHMzShcQ7a/view?usp=sharing. However, when I decompressed the zip file, I only got three files QB-article.csv, QB-video.csv, and QK-video.csv, while the QK-article.csv was not found. I am not sure if I made a mistake or if the file wasn't in the zip package. Would you like to help me check the reason? Very appreciated.

**Comment by yuangh-x** [comment]
Thanks for the reminder! I checked the zip file again and found that the QK-article.csv is in the zip package, maybe it needs to be downloaded again.

**Comment by PeiJieSun** [comment]
Appreciated! Solved.

**Comment by PeiJieSun** [comment]
Sorry to bother you again. I didn't find the timestamp information in the datasets, while in the introduction of the paper https://openreview.net/pdf?id=PfuW84q25y9, the authors claimed that there should have timestamps in the datasets. Will there be a future version of the dataset with timestamps?

**Comment by yuangh-x** [comment]
Sorry to make you confused, we have desensitized the timestamp information, sorted the items clicked by users, and the time information has been retained in each user's click history. The effect after processing is the same as preserving timestamp information.

**Comment by PeiJieSun** [comment]
Got it. I think it is also necessary to keep the time information among different records, as it can help us better process the dataset for further study.
