### ISSUE TITLE
age属性的值的含义

### ISSUE THREAD

**Issue by Zoybzo** [yuangh-x/2022-NIPS-Tenrec#16]
您好，我想请问一下，在QK-video.csv、sbr_data_1M.csv等文件中age属性的值似乎仅包含整数值0-5，这些值分别表示哪个年龄段呢？

**Comment by yuangh-x** [comment]
很抱歉，由于公司对数据隐私性的保护，我们不方便透露数值具体代表的年龄段，还请谅解。
