### ISSUE TITLE
bert4rec的疑问

### ISSUE THREAD

**Issue by xxllp** [yuangh-x/2022-NIPS-Tenrec#20]
bert4rec的dev 负样例和评估跟我看pytorch版本的有些不一样，
1.负样例的个数是全量还是没有参与评估？
 虽然我看到有一些候选集的代码，但是没有使用
2.模型的预测
这块的模型预测代码是否有

**Comment by yuangh-x** [comment]
您好，我们的评估没有使用负采样，而是采用全量评估，因为2020年kdd的best paper指出抽样后的指标不合理。当然我们也提供了负采样的方法，提供给使用者。

**Comment by yuangh-x** [comment]
另外，请问您指的预测代码是什么，这里我不太清楚您想要哪一块的代码。

**Comment by xxllp** [comment]
预测代码指的是infer代码，就是上线后预测结果的代码

**Comment by yuangh-x** [comment]
您好，我们没有直接生成预测结果的代码，不过您可以根据得分进行排序然后产生前n个推荐结果。
