### ISSUE TITLE
can't download dataset

### ISSUE THREAD

**Issue by Hcnaeg** [yuangh-x/2022-NIPS-Tenrec#22]
<img width="567" alt="image" src="https://github.com/yuangh-x/2022-NIPS-Tenrec/assets/51738591/a2f9e9d2-a898-4e3b-ae0f-bd6cea6a82a2">

进入数据集下载页面https://static.qblv.qq.com/qblv/h5/algo-frontend/tenrec_dataset.html
输入相关信息并勾选协议后，显示上述错误，更换邮箱信息依然报错，请问是什么原因呢？🙏

**Comment by yuangh-x** [comment]
你好，我这边刚测试了不同的邮箱地址都可以正常发送下载地址，可能你那边需要确认一下是否是邮箱地址错误或者邮箱设置的问题。
