### ISSUE TITLE
The number of interactions in ctr_data_1M.csv is different from that reported in the paper.

### ISSUE THREAD

**Issue by Xiuchen519** [yuangh-x/2022-NIPS-Tenrec#3]
Hi, author! Thank you for your contribution!
I have a question. Why is the number of interactions in ctr_data_1M.csv different from that reported in the paper? I load the ctr_data_1M.csv and find 120342306 interactions in it. But the number of interactions reported in the paper is 86642580. Do I need to filter some interactions? What strategy did you use to filter interactions? Hope to your reply!

**Comment by yuangh-x** [comment]
I'm glad to answer your question. The number of interactions mentioned in the paper is the number of interactions after sampling, and not the original number of interactions in car_data_1M.csv.

**Comment by Xiuchen519** [comment]
Thank you for your reply. One more question. Did you do the same sampling as CTR task in MTL task? OR you just use all ctr_data_1M in MTL task.

**Comment by yuangh-x** [comment]
Yes, we do the same sampling.

**Comment by Xiuchen519** [comment]
Thank you！
