### ISSUE TITLE
Read-Percentage为什么有超过100的？

### ISSUE THREAD

**Issue by TangJiakai** [yuangh-x/2022-NIPS-Tenrec#8]

**Comment by yuangh-x** [comment]
你好，read_percentage表示文章阅读度，超过一百的表示多次阅读。

**Comment by TangJiakai** [comment]
好的，麻烦再问一下，你们gender是1表示男，还是2表示男？

**Comment by yuangh-x** [comment]
很抱歉这个不能告知您，应腾讯公司要求，用户性别也需要做匿名处理。

**Comment by TangJiakai** [comment]
好的，感谢您！那你们有显式rating的数据嘛？我看了一下好像没有欸，就是比如1-5的评分数据，MovieLens、Amazon等数据集都有的，你们是之后会提供吗？

**Comment by yuangh-x** [comment]
有的，article数据集的item_score属性就是rating数据。

**Comment by TangJiakai** [comment]
emm，sorry 我还是很模糊，
1. 感觉字段有些没搞懂（比如article里面的read，为什么会存在read_percent>0但是read=False的？）
2. 你说的rating是推荐评分系统预测的吧？而不是真正用户给的Ground Truth。
3. video并没有rating相关字段

**Comment by yuangh-x** [comment]
1、关于read_percent>0但是read=False的问题，平台会根据用户的实际阅读时的行为来判断是否真的阅读该文章，当用户误触或者长时间不动时，平台将用户的read设置为False；
2、这里的item_score是包括用户打分、平台打分等，是ground truth，但因为公司要求，我们对这些特征的名字都做了匿名处理；
3、是的，只有article数据集有rating，video没有该字段。

**Comment by TangJiakai** [comment]
tks，贵司匿名的，都是我想要的www

**Comment by TangJiakai** [comment]
为什么video数据集还会出现click=0但是watching times=1的？这怎么解释呢？

**Comment by yuangh-x** [comment]
我们对video数据集的click的设定是，当视频播放时长占视频时长一定百分比的时候才判定为1，意思是一个用户观看了该视频一定的时间才算该用户真正点击该视频。watchtimes是对用户进入该视频次数的记录。

**Comment by TangJiakai** [comment]
> 我们对video数据集的click的设定是，当视频播放时长占视频时长一定百分比的时候才判定为1，意思是一个用户观看了该视频一定的时间才算该用户真正点击该视频。watchtimes是对用户进入该视频次数的记录。

那为什么还会有watching times=1但是like、follow或者share不为0存在的情况？是指用户没播放，单纯做了这几个动作？

**Comment by yuangh-x** [comment]
是的，用户的观看时间没达到阈值，所以不被记录点击行为，但是做了这些动作。

**Comment by TangJiakai** [comment]
可能我没表达清楚，就是video会存在观看时间为0，但是仍然存在like/follow/share为1的case

**Comment by yuangh-x** [comment]
这是因为APP的交互设计的原因，会存在用户在主页面浏览缩略视频窗口时进行一些action或者一些误触，但用户并没有真正点击进入到视频里面。所以会存在一些极少watching times为0，但其他行为为1的case。

**Comment by TangJiakai** [comment]
paper里面说video每个用户都是至少5次数据，但是为啥还是有
![image](https://user-images.githubusercontent.com/58941474/203973246-4b4561c0-1249-4d39-b84a-2fe6042ce317.png)

**Comment by yuangh-x** [comment]
论文中提到，从平台的原始数据库中抽取五次数据以上的用户，但在原始数据处理时会合并或筛选掉一些无效数据。

**Comment by TangJiakai** [comment]
好的，我还有问题哈（感谢您耐心回答，但这些问题估计后面的人也都会提到），就是article中同样的gender（比如下图中为1）对应到video中的gender却不全是一样的
![image](https://user-images.githubusercontent.com/58941474/203995802-6fad74fd-3829-43fa-ab93-88a9dd974e22.png)

**Comment by TangJiakai** [comment]
sorry？是我表达不清楚吗？还是出现这个问题的原因 你不清楚呢？

**Comment by yuangh-x** [comment]
对这个问题的表达我不太清楚。

**Comment by TangJiakai** [comment]
就是说，比如在article里面，gender是1，但是如果我让article和video两个数据集根据user_id合并，对应到video中的gender却不全是一致的，而是0、1、2都会有。正常情况，如果1在article代表男性，那么对应到video中那么性别肯定也是确定某个数字（或者未知），至少不应该出现三种情况啊
